replicas: 3

image:
  repository: pravega/zookeeper
  tag: 0.2.7
  pullPolicy: IfNotPresent

storage:
  className: standard
  # specifying reclaim policy for PersistentVolumes
  # accepted values - Delete / Retain
  reclaimPolicy: Delete
  cacheVolumeRequest: 10Gi
